sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
before_install:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
  - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
  - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
  - aws configure set default.region us-east-2
  - aws configure set output json
  - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.8/2020-04-16/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
  - kubectl version --short --client
  #- kubectl config set-context ${AWS_USER} --cluster=${AWS_CLUSTER} --user=${AWS_USER}
  #- kubectl config use-context ${AWS_USER}
  #- kubectl config set-cluster ${AWS_CLUSTER} --certificate-authority=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EVXlNekV6TXpnMU5Wb1hEVE13TURVeU1URXpNemcxTlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTk5vCjFKSjRaOFNHaHdSY0pTSWZlSkl5SWVYM05Wb3hKV3c1NG52YVBQcHZWZXJxVEJhaXdqUUZvbEZ0K0N0UHB4cjMKRmV1V1F1V3hUTDI1U2JEZjdwWUZWRHl3RHBnQ1dxMzFacHhqcnpQMnJPQVJnc2FrSU1VNU13NTVhRVk4bXNSVgpubk1BeFhOa0dIYXk0Uk1ZdkM3OWEwTU5tRXBiYkFQTWJKRmlzWktlZ2NkekJTcFRtZWVuQ0pDU0d1TE1kYXVICm5UUFNpZW5qQ0NBcDE4Y29UZjN0bjZxUEhVdEV6RGZ1bUFyN0w4cjRzcTNXMzF0UTU2Mnc1YVNKRVZUNTN1L0EKcGEycDc1Y0ZMeDhCaUc3eVpWWEtmb2JHUGJBNTlBQlRKdVVEdzJvQnBBVWJLQlBPaFN4dkJOVVkrZTdYUUFJcwo3UjcrZGxncXV0M2UxN0gyYWk4Q0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJZGFiRDk0REV1RWNSbGhVTXQrVzRHUXlWeVkKeWlLdk9XTUY0bTNCZ1o3dGk4UlB5b1FmdXFwdTVIazdOU1hlaFJpSVlFS1hXalpDZFc0Vm9FK3pGVEtoNEU4ZAowMkRaNUp2RmJYVWtTVEw5bEFyODM2K3BIaXBwOFNHVkJhdXlOZGhlT2hrWVhibG5JRThoSUhmRm1hejRhRXBIClBvd3dYSm5QQksySDl6dkFmUVF3Qk5XYmpvQlhLVUQvd3JkWDlXU0xRZGJHV01kZzdyNkhCTzIxSkxjODV5WVoKSlhlVGs2Y1k5WFdnZm13ZFJFR3RCYnAwaDdCajFsM1Jrb1pKNExLdklTYkg4SmFPNFFmWlVPc28rUThSejVVYwpsUFQ0L1VzRTU5SU1wTVhZS2VNTUdSUmRMOENnQTFEb1NCUktRRmdJU0p1SmsxcWtmYmx4Z1BSL1FQcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo= --server=${AWS_CLUSTER_SERVER}
  #- kubectl config view
  #- kubectl get nodes
  - aws eks list-clusters
  - aws eks --region us-east-2  update-kubeconfig --name attractive-gopher-15902406072
  - kubectl get svc
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t thandotettey/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thandotettey/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
